ログイン・ログアウト機能
shinonome-inc/backend-final-assignment-asahi pull request #2
Opened 2024-01-10 21:47 UTC by Ash1ey18

## 受講生の確認事項

- [] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [] 作成したモデルを全てDjango管理画面に登録した
- [] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-01-12 19:26 UTC, Shiota620 commented on mysite/settings.py
> +LOGIN_REDIRECT_URL = "/accounts/user_profile/"
LOGIN_REDIRECT_URLはtweets.homeとしてください

2024-01-13 03:27 UTC, Shiota620 requested changes
もしかすると、後ほどレビュー内容を追加する可能性があります。

2024-01-13 03:27 UTC, Shiota620 commented on mysite/settings.py
> +LOGIN_REDIRECT_URL = "/accounts/user_profile/"
LOGIN_REDIRECT_URLはtweets.homeとしてください

2024-01-13 03:27 UTC, Shiota620 commented on templates/registration/login.html
templates/accounts/login.htmlの階層になるように変更してください。

2024-01-13 03:27 UTC, Shiota620 commented on accounts/tests.py
> +class TestLoginView(TestCase):
テストでユーザーログインを行う場合はself.client.loginまたはself.client.force_loginでログイン処理してください。

2024-01-13 03:27 UTC, Shiota620 commented on mysite/settings.py
> +LOGIN_REDIRECT_URL = "/accounts/user_profile/"
また、最終課題レビューポイントでは、
LOGIN_URL、
 LOGIN_REDIRECT_URL、
LOGOUT_URL
以上3点の記載があることが要求されています。
これに即した形にコードを変更してみてください。

2024-01-13 03:48 UTC, Shiota620 requested changes
追加のコメントです。

2024-01-13 03:48 UTC, Shiota620 commented on .vscode/settings.json
こちらのファイルの変更に関して、変更理由をお聞かせいただきたいです。

2024-01-14 01:32 UTC, Ash1ey18 commented on .vscode/settings.json
tokiさんこんにちは！asahiです！コメントありがとうございます！🙏
settings.jsonの変更について、それぞれ回答させていただきます。

１．source.organizeImports
「🎉 ログイン・ログアウト機能実装開始」にて、デフォルトのtrueから”explicit”に変更していたところを「🔧 設定ファイルの更新」にてtrueに戻した形になります。一度”explicit”に変更した理由は、”explicit”と変更したときの挙動を知りたかったからです。紛らわしい変更を加えてしまい、申し訳ありません。今後はコミットに反映しないように実験したいと思います。

２．editor.formatOnSave
こちらはtemplatesファイル（htmlファイル）を保存すると不自然なフォーマットを実行してしまい、エラーが吐かれたのでfalseにさせていただいています。

３. python.analysis.typeCheckingMode
feature/signupブランチの「🔧 ログの消去、設定の追加」にて、元々なかった設定であるtypeCheckingModeを導入していました。しかし期待しない部分でエラーが出てしまい、今回の開発においては不必要なものと判断したため、削除いたしました。

+α

４．python.analysis.autoImportCompletions
こちらもfeature/signupブランチの「🔧 ログの消去、設定の追加」にて導入していました。現時点で問題なく使用できているのでそのまま残してあります。
    
長文になってしまいましたが、
確認いただければ幸いです！🙏

2024-01-14 01:55 UTC, Ash1ey18 commented on accounts/tests.py
asdf

2024-01-14 02:53 UTC, Ash1ey18 commented on accounts/tests.py
> +class TestLoginView(TestCase):
TestLoginViewについて、self.client.loginを使用するとテストの要件を確認できないので、self.client.postを使用しています。
TestLogoutViewのsetUp内のユーザーログインについては、元々self.client.loginを使用しています！

2024-01-14 03:01 UTC, Ash1ey18 commented
tokiさん！asahiです！レビューありがとうございました！🙏
・LOGIN_URL, LOGOUT_URLの追加
・templatesにおける階層構造の変更（accounts/login.htmlに修正）
以上の２点を修正しました！✨
また、self.client.loginを使用する部分が具体的に分からなかったので教えていただけると幸いです！
そして、setting.jsonについての返信もしましたのでご査収ください！

2024-01-14 10:02 UTC, Shiota620 commented on .vscode/settings.json
お答えいただき、ありがとうございます。
大変勉強になりました。

2024-01-14 10:23 UTC, Shiota620 commented on accounts/tests.py
> +class TestLoginView(TestCase):
申し訳ございません。見落としてました。
TestLoginViewに関しては私が最終課題を行ったときも同じ形式でレビュワーの方からOKを貰ったのでおそらく問題ないと思います。

2024-01-14 10:44 UTC, Shiota620 reviewed
1次レビューはこれで終了となります。お疲れ様でした。


2次レビューよろしくお願い致します。

もし、1次レビューにてレビューポイントを満たしていなかった場合、よろしければ今後の参考のために私のSlack(toki / TokiShiota)の方にメッセージを送っていただけるとありがたいです

2024-01-14 12:04 UTC, Akinori13 requested changes
いくつかコメントしました！

2024-01-14 12:04 UTC, Akinori13 commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
一般的にはtrueにしている方が多い印象ですが、書き間違いなどではないですか？
個人の趣向であれば全然かまわないです。

2024-01-14 12:04 UTC, Akinori13 commented on accounts/views.py
> +
不要なimportは削除しましょう

2024-01-14 12:04 UTC, Akinori13 commented on accounts/views.py
> +from django.contrib.auth.views import LoginView
修正不要ですが、このようにすることで、重複した命名を回避して、LoginViewという名称でViewを作成することもできます。
```
from django.contrib.auth import views as auth_views
class LoginView(auth_views.LoginView):
    ...
```

2024-01-14 12:04 UTC, Akinori13 commented on accounts/views.py
> +class UserProfileView(TemplateView):
このViewはログイン必須にしましょう。
※[こちら](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview#gid=1308498917)の最下部に「下線はログイン限定画面を示す」と記載されているはずです！（読みづらいところに書いてしまい申し訳ないです）

2024-01-14 12:04 UTC, Akinori13 commented on templates/accounts/profile.html
> +  </form>
ログアウトは共通のパーツなのでbase.htmlの方がよいですね。
若干高度かもしれないですが、ログイン状態のときはログアウトボタンが、ログアウト状態のときはログインとサインアップボタンが表示されるみたいにもできるはずです！

2024-01-15 05:25 UTC, Ash1ey18 commented on accounts/views.py
> +from django.contrib.auth.views import LoginView
trueにすると、templatesファイル（htmlファイル）を保存する際に不自然なフォーマットをしてしまっていたので、falseにさせていただいています！

2024-01-15 06:00 UTC, Ash1ey18 commented on templates/accounts/profile.html
> +  </form>
akinoriさん！asahiです！レビューありがとうございました！！
指摘された部分を修正しました！！

同じ名前のクラスを作成できるのは初耳でした！
コードが見やすくなるアドバイスも本当にありがたいです🙏
めちゃくちゃ勉強になりました！！✨

最後にbase.htmlの部分ですが、ログアウトしているときには他人のツイートを閲覧できない仕様になっているのでログアウト状態の場合に「ログイン」ボタンを設置する意味がないと判断しました！ですので、ログイン状態の場合のみに「ログアウト」ボタンを設置するコードに変更しました！！

ご確認いただければ幸いです！

2024-01-17 14:11 UTC, Akinori13 commented on templates/base.html
> +      {% if request.path != "/" and request.path != "/accounts/signup/" and request.path != "/accounts/login/" %}
is_authenticatedメソッドを使ってあげましょう！
参考：https://itc.tokyo/django/dynamic-links-by-user-info/

2024-01-18 23:02 UTC, Ash1ey18 commented on templates/base.html
> +      {% if request.path != "/" and request.path != "/accounts/signup/" and request.path != "/accounts/login/" %}
Akinoriさんコメントありがとうございます！！
こんな便利メソッドがあるのですね！！勉強になりました！👍

2024-01-19 02:08 UTC, Akinori13 commented
LGTM

2024-01-19 02:08 UTC, Akinori13 approved these changes

2024-01-19 02:09 UTC, merged