ツイート機能
shinonome-inc/backend-final-assignment-asahi pull request #3
Opened 2024-01-28 23:03 UTC by Ash1ey18

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-02-06 11:42 UTC, ryo-thel reviewed
良くかけていると思います！
１点だけ修正をお願いします！

2024-02-06 11:42 UTC, ryo-thel commented on tweets/views.py
> +
get_querysetをオーバライドしたことでordering属性の呼び出しを上書きしてしまい、ソートが機能しない状態になってしまっているので修正をお願いします！

https://ccbv.co.uk/projects/Django/5.0/django.views.generic.list/ListView/

2024-02-07 09:21 UTC, Ash1ey18 commented
ryoさん！レビューありがとうございました！！✨
ordered_byメソッドによってソートを実装し直しましたのでご確認ください！🙏

2024-02-07 18:44 UTC, ryo-thel commented
LGTM

2024-02-08 07:03 UTC, IzmYuta requested changes
全体的によく書けていると思います！👍 
数点コメントしたので確認&修正お願いします！！ 🙏

2024-02-08 07:03 UTC, IzmYuta commented on tweets/tests.py
> +            f"この値は 140 文字以下でなければなりません( {len(invalid_data['content'])} 文字になっています)。",
文字数を、数値をハードコードせずにlen()で取得している点がとても良いと思いました 👍 
f文字列を使いこなしているのも素晴らしいと思いました 💯

2024-02-08 07:03 UTC, IzmYuta commented on tweets/views.py
> +    fields = ["content"]
formのフィールドはforms.pyで定義するのが良いです。
ファイルごとに役割を分割して管理することで、コードが膨大化した時でも効率的に変更が行えるためです。

2024-02-08 07:03 UTC, IzmYuta commented on tweets/models.py
> +        return f"{self.user.username} - {self.content} ({self.created_at})"
Good 👍 
ところで`__str__`はどのようなものか説明できますか？

2024-02-09 01:55 UTC, Ash1ey18 commented on tweets/models.py
> +        return f"{self.user.username} - {self.content} ({self.created_at})"
Modelにおける`__str__`は、Djangoの管理画面内でModelオブジェクトの表示方法を設定するメソッドです！機能の実装には不要でしたが、練習で書いてみました！💪

2024-02-09 02:17 UTC, Ash1ey18 commented
Yutaさん！コメントありがとうございます！！🙇🏿
勉強になりました！！✨

2024-02-09 14:18 UTC, IzmYuta commented on tweets/models.py
> +        return f"{self.user.username} - {self.content} ({self.created_at})"
💯

2024-02-09 15:54 UTC, IzmYuta requested changes
追加で修正お願いします！ 🙏

2024-02-09 15:54 UTC, IzmYuta commented on accounts/tests.py
> +        self.tweet2 = Tweet.objects.create(user=self.user, content="tester2 tweet")
`Tweet.objects.create`において、ユーザーはログインしている必要はありません。
これは、Djangoの機能でツイートを作成しているのであって、ログイン必須である`tweets/create`エンドポイントから作成しているわけではないからです。
ちなみにユーザーの指定は`user=self.user`の部分で行っています。

2024-02-09 15:54 UTC, IzmYuta commented on accounts/tests.py
> +        self.tweet2 = Tweet.objects.create(user=self.user, content="tester2 tweet")
また、`self.user`変数を使い回して、別のオブジェクトを再代入するのは、特別な意図がない限りは避けた方が無難です。
同じ変数(名)に複数の役割を持たせることになり、この変数がどんな役割も持っているかを、行ごとに常に考える必要が出てくるからです。
306行目と311行目にコメントを残していて、わかりやすくしている点は素晴らしいですが、コメントを付けずとも理解できるように変数名を工夫するとなお良いです。

2024-02-09 15:54 UTC, IzmYuta commented on accounts/tests.py
> +        self.tweet2 = Tweet.objects.create(user=self.user, content="tester2 tweet")
長くなりましたが、以上を踏まえて次のように修正お願いします🙏 
そのままコピーでも、自分の好きなように変えても大丈夫です。
```python
    def setUp(self):
        self.dummy_user = User.objects.create_user(username="dummy", password="dummypassword1")
        self.tweet1 = Tweet.objects.create(user=self.dummy_user, content="dummy tweet")
        self.user = User.objects.create_user(username="tester", password="testpassword1")
        self.tweet2 = Tweet.objects.create(user=self.user, content="tester tweet")
        # テスト時にはログイン必要のため
        self.client.login(username="tester", password="testpassword1")
```

2024-02-09 15:54 UTC, IzmYuta commented on tweets/tests.py
> +        self.user = User.objects.create_user(username="tester2", password="testpassword2")
こちらも同様に`user2`のような変数名をつけましょう。
他の関数(`test_failure_post_with_not_exist_tweet(self):`など)で使い回す予定のない変数はselfをつけずに定義して大丈夫です。

2024-02-09 15:58 UTC, IzmYuta commented on tweets/forms.py
> +User = get_user_model()
Userは不要です。

2024-02-10 06:56 UTC, Ash1ey18 commented
Yutaさん！コメントありがとうございます！🙏
テスト実装に対する理解が深まりました！！✨

2024-02-13 04:14 UTC, IzmYuta approved these changes
LGTM

2024-02-13 07:37 UTC, merged