フォロー機能
shinonome-inc/backend-final-assignment-asahi pull request #4
Opened 2024-02-11 02:46 UTC by Ash1ey18

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-02-15 10:11 UTC, Rei-Goda reviewed
全体的によくできていていると思います！２点コメントしました

2024-02-15 10:11 UTC, Rei-Goda commented on templates/base.html
>            <li><a href="{% url 'welcome:welcome' %}">Twitter Clone</a></li>
初期の画面に飛んでしまうため、urlをtweets:homeに変更してください

2024-02-15 10:11 UTC, Rei-Goda commented on accounts/tests.py
> +class TestFollowView(TestCase):
フォロー機能のテストはよくできていてGoodです！
追加でTestUserProfileViewのtest_success_getにフォロー数,フォロワー数のテストをお願いします（テスト要件項目の4.フォロー機能No.1を参考に）

2024-02-17 08:26 UTC, Ash1ey18 commented
Hagemuさん！こんばんは！あさひです！
この度はレビューしてくださりありがとうございました！
指摘された2点について修正を加えましたので、ご確認いただければ幸いです！
( [templates/base.html](https://github.com/shinonome-inc/backend-final-assignment-asahi/pull/4/files/8c3261af3e240eb610458b582c6bb58e2e1b3502#diff-690b81fad8df2a1f1ce37c846641d9247e3472d244f17039d2910a5ed0c98d5e)の点について、ログイン前と後で指定URLを分岐させてみました！ )

2024-02-17 15:50 UTC, Rei-Goda commented
修正ナイスです！
1次レビューLGTMです

2024-02-24 04:57 UTC, TAK848 requested changes
testも丁寧で良いと思います！3点ご確認お願いします！

2024-02-24 04:57 UTC, TAK848 commented on mysite/settings.py
> +SQL_DEBUG = True
mainにmergeする=本番の環境でその状態で動く，ということなので，ハードコードでTrueとはしない方が良いかと思います。
Falseにしておきましょう！

（実際のproductionでは，環境変数を見て，ENVがlocalやdev(開発環境)ならTrueとする，みたいな扱いをすることが多いかなと思います）

2024-02-24 04:57 UTC, TAK848 commented on templates/accounts/profile.html
> +<!-- 閲覧するプロフィールがその人自身のものでない場合 -->
[IMO]
これだと，HTMLのコメントとしてfrontendに配信されてしまうので（ブラウザで検証すると見れます），Djangoのcommentタグを使うと良いかもですね
大手企業のページなどでもこんな感じにコメント残ってたりするケースも結構ありますが……

2024-02-24 04:57 UTC, TAK848 commented on accounts/views.py
> +        following_user = User.objects.get(username=self.username)
こちらについて，テスト要件にはないですが，`get`に失敗した場合500が帰ってきてしまっているので，エラーハンドリング（適切なステータスコードでのレスポンス）お願いします！

2024-02-26 11:10 UTC, Ash1ey18 commented
TAKさん！レビューありがとうございました！🙏
修正しましたのでご確認よろしくお願いします！！🙇🏻

2024-02-28 12:08 UTC, TAK848 approved these changes

2024-02-28 12:09 UTC, tak848 commented
LGTM

![LGTM](https://images.lgtmgen.org/007004bb-5893-4cc9-9bc1-496bfb7580d0)

2024-03-02 05:08 UTC, merged